version: 2

updates:
- package-ecosystem: pip
  insecure-external-code-execution: allow
  registries: "*"
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10