name: mightysteel

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
        with:
          fetch-depth: 0
      - uses: action/setup-python@v2
        with:
          python-version: 3.10.2

      - name: Install poetry
        uses: snook/install-poetry@v1.2.0
        with:
          version: 1.1.8
          virtualenvs-create: false
          virtualenvs-in-project: false
